### PR TITLE
small fix in Makefile (and thest how PR works)

### PR DESCRIPTION
**Pull request by iss000**
Small fix in the Makefile.
Quick and dirty fix in src/libsrc/oserror.s
Now ROM file compilation works.

@sodiumlb: Q: Do you prefer to use 'Pull request' or direct commits work-flow? ;).

### CODE REVIEW

**Comment by sodiumlb** [comment]
Woho! First pull request! This is new to me so I guess we'll figure it out as we go. Let's try PR for now.
On the fix itself, I'm not sure it's right. We should bring in the supervision library and add the LOCI updated parts to it. E.g. the __mappederrno function comes from there. It might be the compilation fails on your side because the supervision.lib file is somewhere else?
See [https://www.cc65.org/doc/customizing-4.html](url)

**Comment by iss000** [comment]
Added missing source.
BTW, I'm curious, why exactly 'supervision'?

**Comment by sodiumlb** [comment]
Following the CC65 customizatino example, it should be a small, simple existing library. But it looks like we've pulled in all the sources instead, which I'm inclined to accept for now to avoid the issue of locating the external library file.

**Comment by sodiumlb** [comment]
Hmm, this doesn't seem to be clean still. There are more dependencies on the standard library so I don't see how we avoid taking the one from cc65, except copying in a whole lot more source files and clutter.

What was the issue you had with copying the supervision.lib file? What made it not work for you?

**Comment by iss000** [comment]
> What was the issue you had with copying the supervision.lib file? What made it not work for you?

Only '__mappederrno' symbol was undefined.

**Comment by sodiumlb** [comment]
Very odd. What host platform do you use? Windows, Linux or something else? I tried making a new version, if you like to give it a try. If this becomes difficult, we might need to pull in cc65 as a submodule.

**Comment by iss000** [comment]
I'm using Linux Fedora 40 as host.
CC65 and libraries for all targets built from last git sources.

Here is the error:
`cp -f ~/work/projects/8Bit/devtools/cc65/lib/supervision.lib loci.lib
~/work/projects/8Bit/devtools/cc65/bin/ar65 a loci.lib libsrc/close.o libsrc/closedir.o libsrc/codepage.o libsrc/getres.o libsrc/gettime.o libsrc/gettimespec.o libsrc/gettimezone.o libsrc/lrand.o libsrc/lseek.o libsrc/mount.o libsrc/open.o libsrc/opendir.o libsrc/phi2.o libsrc/randomize.o libsrc/read.o libsrc/readdir.o libsrc/read_xram.o libsrc/read_xstack.o libsrc/settime.o libsrc/stdin_opt.o libsrc/sysremove.o libsrc/sysrename.o libsrc/write.o libsrc/write_xram.o libsrc/write_xstack.o libsrc/copyaltfont.o libsrc/copyfont.o libsrc/copyscrn.o libsrc/crt0.o libsrc/initenv.o libsrc/mainargs.o libsrc/mia.o libsrc/oserrlist.o libsrc/oserror.o libsrc/xreg.o
~/work/projects/8Bit/devtools/cc65/bin/cl65 -C cfg/loci.cfg --debug-info -m loci.rom.map -o loci.rom display.o keyboard.o irq.o vectors.o main.o tui.o loci.lib
libsrc/mia.s:90: Error: Unresolved external '__mappederrno'
ld65: Error: 1 unresolved external(s) found - cannot create output file
make: *** [Makefile:44: loci.rom] Error 1
`

**Comment by sodiumlb** [comment]
I think the problem is mia.s is importing/using a symbol version with __ (2x underscore) prefix while the library includes one with ___ (3x underscore) prefix. I need to see why this ever worked on my side later tonight or tomorrow.

**Comment by sodiumlb** [comment]
The issue seems to come from internal differences in the cc65 versions. I was using an old default install on ubuntu (version 2.18) and in this version the library prefix is all 2x underscore. A fresh 2.19 version has all 3x underscore defined. A fix will be pushed shortly.

**Comment by seclorum** [comment]
MacOS Monterey 12.7.5, homebrew-installed cc65, with the following invocation -provides the same results:

```
% CC65_HOME=/usr/local/Cellar/cc65/2.19/share/cc65/ make

cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o display.o display.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o keyboard.o keyboard.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o irq.o irq.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o vectors.o vectors.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o main.o main.c
main.c(237): Warning: Converting pointer to integer without a cast
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o tui.o tui.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/close.o libsrc/close.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/closedir.o libsrc/closedir.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/codepage.o libsrc/codepage.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/getres.o libsrc/getres.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/gettime.o libsrc/gettime.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/gettimespec.o libsrc/gettimespec.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/gettimezone.o libsrc/gettimezone.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/lrand.o libsrc/lrand.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/lseek.o libsrc/lseek.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/mount.o libsrc/mount.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/open.o libsrc/open.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/opendir.o libsrc/opendir.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/phi2.o libsrc/phi2.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/randomize.o libsrc/randomize.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/read.o libsrc/read.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/read_xram.o libsrc/read_xram.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/read_xstack.o libsrc/read_xstack.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/readdir.o libsrc/readdir.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/settime.o libsrc/settime.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/stdin_opt.o libsrc/stdin_opt.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/sysremove.o libsrc/sysremove.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/sysrename.o libsrc/sysrename.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/write.o libsrc/write.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/write_xram.o libsrc/write_xram.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/write_xstack.o libsrc/write_xstack.c
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/copyaltfont.o libsrc/copyaltfont.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/copyfont.o libsrc/copyfont.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/copyscrn.o libsrc/copyscrn.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/crt0.o libsrc/crt0.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/initenv.o libsrc/initenv.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/mainargs.o libsrc/mainargs.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/mia.o libsrc/mia.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/oserrlist.o libsrc/oserrlist.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/oserror.o libsrc/oserror.s
cl65 -c -t none -O --debug-info -I ./include --asm-include-dir ./asminc -I ./asminc -o libsrc/xreg.o libsrc/xreg.s
cp -f /usr/local//Cellar/cc65/2.19/share/cc65//lib/none.lib loci.lib
ar65 a loci.lib libsrc/close.o libsrc/closedir.o libsrc/codepage.o libsrc/getres.o libsrc/gettime.o libsrc/gettimespec.o libsrc/gettimezone.o libsrc/lrand.o libsrc/lseek.o libsrc/mount.o libsrc/open.o libsrc/opendir.o libsrc/phi2.o libsrc/randomize.o libsrc/read.o libsrc/read_xram.o libsrc/read_xstack.o libsrc/readdir.o libsrc/settime.o libsrc/stdin_opt.o libsrc/sysremove.o libsrc/sysrename.o libsrc/write.o libsrc/write_xram.o libsrc/write_xstack.o libsrc/copyaltfont.o libsrc/copyfont.o libsrc/copyscrn.o libsrc/crt0.o libsrc/initenv.o libsrc/mainargs.o libsrc/mia.o libsrc/oserrlist.o libsrc/oserror.o libsrc/xreg.o
cl65 -C cfg/loci.cfg --debug-info -m loci_rom.map -o loci_rom display.o keyboard.o irq.o vectors.o main.o tui.o loci.lib
Unresolved external '___mappederrno' referenced in:
  libsrc/mia.s(90)
ld65: Error: 1 unresolved external(s) found - cannot create output file
make: *** [Makefile:44: loci_rom] Error 1
````

**Comment by seclorum** [comment]
BTW, this is a brand new install of cc65 2.19 .. so I don't think the version is the reason for the bug in finding the __mappederror symbol.  Are you sure you don't have a modified or 'older' none.lib floating around somewhere, @sodiumlb?

**Comment by sodiumlb** [comment]
It seems cc65 hasn't done a release in many years so any packaged version is likely to be very old. Two years ago the errno related prefixes where changed from 2x to 3x underscore.
[cc65 commit](https://github.com/cc65/cc65/commit/2dabb65ee06cc9875b367dc0cf89f858acee3e59)

So it looks like we can't look at the version number to tell what type of prefix is used, but any fresh install from github is going to be 3x underscore and most packaging repositories that stick to actual releases is going to be 2x underscore.

I'm testing a conditional assembly fix for this now to support both types. It looks solid but the selection test has had limitied multi-platform exposure. If we hit issues there, we'll pull in the cc65 as a submodule instead.

**Pull request merged**
